"""Initial migration

Revision ID: xxxxxxxxxxxx
Revises: 
Create Date: 2024-xx-xx

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel import SQLModel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'xxxxxxxxxxxx'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ... rest of the generated code ...
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ... rest of the generated code ...
    pass 